### ISSUE TITLE
Misleading content library

### ISSUE THREAD

**Issue by yarodevuci** [sleepwalkerfx/RMGradientView#2]
I tried to create same gradient color like here
https://uigradients.com/#CoolBlues

Instead I am getting just a mix with two colors... half and half. It's not a gradient.

**Comment by yarodevuci** [comment]
I removed gradientLayer.locations and it seemed did the trick
But It created some weird artifacts, like huge pixels
![simulator screen shot - iphone 8 - 2018-07-17 at 15 16 15](https://user-images.githubusercontent.com/13408859/42848469-85c10e3a-89d4-11e8-911e-dd8637d02ed5.png)

`gradientLayer.contentsScale = UIScreen.main.scale` did not helped.. 
@sleepwalkerfx

**Comment by sleepwalkerfx** [comment]
Not sure why you weren't able to get the gradient.  Here's a simple video how you would achieve the desired effect.
https://www.youtube.com/watch?v=JA_I5EXuthc
However this component requires you to set 3 gradient points. Since you want a 2 point gradient, best way to do this is colorpick the middle point of that gradient and set that value in property inspector.

**Comment by yarodevuci** [comment]
@sleepwalkerfx ok, thank you, will try that
